# syntax=docker/dockerfile:1

ARG XX_VERSION=1.4.0
ARG RUST_VERSION=1.77
ARG ALPINE_VERSION=3.19

ARG TARGETPLATFORM

# xx is a cross-compilation helper
FROM --platform=$BUILDPLATFORM tonistiigi/xx:${XX_VERSION} AS xx

FROM --platform=$BUILDPLATFORM rust:${RUST_VERSION}-alpine${ALPINE_VERSION} AS build
RUN apk add bash clang git openssl-dev lld wget
COPY --from=xx / /

RUN mkdir /build && \
    cd /build && \
    git clone https://github.com/packom/mbus-httpd
